### ISSUE TITLE
Problem updating engrams

### ISSUE THREAD

**Issue by WWW-CrossArkEvolved-COM** [thommcgrath/Beacon#49] opened 2017-06-06 16:03 UTC
When attempting to update the engrams it gives an error and when I looked on here the site I seen I could download them but couldn't figure out how to install them, any advice?  Also when I hit check for updates it says something seems to be wrong please report this problem to be fixed.. so here I am lol =) Thanks for all your hard work

**Comment by thommcgrath** [comment] 2017-06-06 16:06
First, let's get your engrams updated. Once you download the json file, just use File -> Import to import it.

Second, diagnosing your update issue. Are you on Windows 7 by chance? Is your version up to date according to the version listed on https://thezaz.com/beacon?

**Comment by WWW-CrossArkEvolved-COM** [comment] 2017-06-06 16:09
Thanks Engrams Update Achieved! =)  and yes on Windows 7 and the version is up to date in the about section on beacon I believe 1.0.0b7

**Comment by thommcgrath** [comment] 2017-06-06 16:12
Ok, since you're on Windows 7, the issue is almost certainly this: https://support.microsoft.com/en-gb/help/3140245/update-to-enable-tls-1.1-and-tls-1.2-as-a-default-secure-protocols-in-winhttp-in-windows - the link has easy methods to fix the problem too.

The Beacon installer should have applied this automatically, but for safety reasons I coded it not to mess with things that had previously been customized. So there are ways that TLS 1.2 support may not have been enabled by the Beacon installer.

This is one of those updates that every copy of Windows should have enabled, but for some reason Microsoft lists as optional, so most copies don't get it.

**Comment by WWW-CrossArkEvolved-COM** [comment] 2017-06-06 16:16
Alright cool I'll check it out thank you.  Also before I updated my engrams I manually added class stings in my library for stuff like the Hyaenodon Saddle but now that is updated should I go back and change it or will it still work as is?

**Comment by thommcgrath** [comment] 2017-06-06 16:16
It will work as-is.

**Comment by WWW-CrossArkEvolved-COM** [comment] 2017-06-06 16:26
You are the man!  I was also curious if there is a way to mass update my drops like when I edit something in my preset library can I make it apply the changes to all the drops at once?  Also I had underwate drops set to have two items but sometimes only get one in the drop and I had it set to ascendant quality but it would randomly give as low as journeyman (I know it will vary occasionally but does locking the quality help with that?) Sorry for all the questions lol

**Comment by thommcgrath** [comment] 2017-06-06 16:30
Heh.

Best way to mass update is to multi-select. Grab more than loot source, and the item sets that are identical will be shown. Then you can right-click each set and choose "Reconfigure from preset" and they'll all get rebuilt.

Quality is the biggest issue given how much randomness Ark introduces. Beacon uses statistics to do its best to get you the quality you ask for, but until Wildcard removes the random quality multiplier I can't make it perfect. Quantity is not something I've ever had an issue with though.

**Comment by WWW-CrossArkEvolved-COM** [comment] 2017-06-06 16:32
Ah ok so that far of a variation of quality is normal though correct?  As far as the min max items received in the drops I will continue to monitor and I will let you know if I figure out whats going on with that.

**Comment by thommcgrath** [comment] 2017-06-06 16:35
Yeah, there's quite a range. The value Beacon uses for Mastercraft, for example, only actually gives Mastercraft about 50% of the time. 25% of the time it produces Ascendant and 25% of the time it produces Journeyman. And this was the most statistically correct value I could use. Change the value up or down, and the chances sway farther from that 50%.

Mastercraft seems to be the most extreme case, but all the values can sway quite a bit more than I'd like.

**Comment by WWW-CrossArkEvolved-COM** [comment] 2017-06-06 16:45
Awesome thanks the deff helps to know.  About the quantity I was wondering if it was better to have for example my underwater drop I have one main preset it uses but I want it to give me no less or more than two items from that preset so is it better to set the loot source to have 2 min and 2 max presets and uncheck prevent duplicates or should I prevent duplicates and set that min and max to 1 and then just within the preset set the min and max to 2?

**Comment by thommcgrath** [comment] 2017-06-06 16:48
I keep prevent duplicates checked, and would set the min and max to 2. That's how I do some of my own, and I've never seen it pick more or less.

**Comment by WWW-CrossArkEvolved-COM** [comment] 2017-06-06 16:50
Ok cool so with one item set (that contains a bunch of items) if i have the loot source set to min max 2 item sets with prevent duplicates checked that will result in it choosing two items from my preset correct?

**Comment by thommcgrath** [comment] 2017-06-06 16:50
Correct

**Comment by WWW-CrossArkEvolved-COM** [comment] 2017-06-06 16:52
=) Thank you for your help and patience your a saint.  Final Question lol Underwater Blue Yellow Red and Deep Sea are all the Underwater Rare Crates Correct? How do I know where those ones are located on the map?  I know where the underwater crates spawn I just didnt know where yellow vs blue is.

**Comment by thommcgrath** [comment] 2017-06-06 16:55
Deep Sea are on the ocean floor. The others are in the underwater caves.

**Comment by WWW-CrossArkEvolved-COM** [comment] 2017-06-06 16:55
Ah ok that makes sense thanks a million!!!! Have a good one man for sure!

**Comment by thommcgrath** [comment] 2017-06-06 16:56
No problem. I'm going to close this issue now.

**Closed by thommcgrath** 2017-06-06 16:56 UTC
