### ISSUE TITLE
Scorched Earth MinQualityPrimitiv Issue

### ISSUE THREAD

**Issue by VorsGesicht** [thommcgrath/Beacon#23] opened 2017-01-15 15:05 UTC
You script say Primitiv Quality is 0 but Primitiv is 1

YOURS script: MinQuality=0.000000,MaxQuality=0.000000,

in Original: MinQuality=1.0,MaxQuality=1.0

Pls fix it and great work Dude

**Comment by VorsGesicht** [comment] 2017-01-16 07:00
Ok next issue found in the Scorched Earth List NumItemsPower=0.00000 is not correct same issue but other Command^^ pls let it grow up to 1.0 Thanks

**Comment by thommcgrath** [comment] 2017-01-16 19:25
Can you attach your files so I can see what you mean? Are you importing an existing Game.ini?

**Comment by VorsGesicht** [comment] 2017-01-17 14:17
If i choose Primitiv by Quality your script will write MinQuality=0.000000,MaxQuality=0.000000. But Primitiv is 1.00000. Next Issue is with this command NumItemSetsPower=0.000000 the Developer say this Boolean is everytime 1 or you will get too high Item's...

i added the file that createt your Beacon Version 1.0.0 Beta Build 8
[GameBeacon.txt](https://github.com/thommcgrath/Beacon/files/711252/GameBeacon.txt)

**Comment by thommcgrath** [comment] 2017-01-17 21:46
Ok, I'll fix the issue with NumItemsSetsPower, though I'm pretty sure it makes no difference at all. I've been using a set designed by Beacon for months, and the qualities feel very much as intended.

As for the quality codes, don't worry about that. Don't trust the wiki either. The values used are computed from the loot source's built-in multipliers and a statistical sampling of a very large amount of item spawning. There's a lot of math going on behind the scenes, Beacon is not simply inserting the values provided by the wiki.

**Comment by thommcgrath** [comment] 2017-01-17 21:55
Fixed with cdfd948

**Closed by thommcgrath** 2017-01-17 21:55 UTC
