### ISSUE TITLE
[Feature] Another way to add unsupported engrams and things

### ISSUE THREAD

**Issue by Fing3rz** [thommcgrath/Beacon#227] opened 2021-07-28 11:35 UTC
I recently learned of a mod on the workshop called [DataDumper](https://steamcommunity.com/sharedfiles/filedetails/?id=2171967557
). It outputs engram/item data to the server console which can then be saved to the server log. It is intended for Ark Server Manager but could this be used to quickly add unsupported mod data to Beacon?
To use the mod you just start a server with logging enabled, the mods you want to dump and the DataDumper mod loaded last. Wait for it to boot up completely and the info will dump to the console automatically, then shutdown the server and browse the log. I've uploaded a test sample I ran with only Structures Plus installed.
[ShooterGame.log](https://github.com/thommcgrath/Beacon/files/6892754/ShooterGame.log)

**Comment by thommcgrath** [comment] 2021-07-28 12:58
Ok I am a fan of this idea. Looking over the data, the main challenge I see is identifying which ones need to be imported. This data includes everything loaded into the game, and I'm sure people will run this with many mods. The update I would include this in allows users to define as many local mods as they want, no longer confined to just one. And thanks to the S+/SS/N+ fiasco, paths are not globally unique.

So... I think the basic way to handle this is:
- Only consider paths that start with `/Game/Mods/`.
- Prompt the user to choose the mod paths that should be imported, such as `/Game/Mods/StructuresPlusMod/`.

With those two behaviors, the user could run the process multiple times, each time selecting different mod paths if they wanted to organize.

**Comment by Fing3rz** [comment] 2021-08-16 05:52
Is this being added to the next build? Do I need the paid edition?

**Comment by thommcgrath** [comment] 2021-08-16 05:54
You should expect this in version 1.5.2, and it does not require the paid edition.

**Comment by Fing3rz** [comment] 2021-08-19 04:02
I didn't even realize there were beta releases. Happy to have found them and started testing this new feature. Seems to be working great! I went ahead and purchased anyways. I really appreciate the work! If I may make a suggestion though.

Instead of manually registering/naming each mod individually, is it possible for them to be generated by the import process? Since you are already grabbing the mod names from the blueprint path so that the user can select which mod engrams to import.

I'm also unable to delete the mods that I have registered from the list. I'm new to the program so maybe it's user error. v1.5.2b2

**Comment by thommcgrath** [comment] 2021-08-19 04:14
It is this way because the mod creation has to come first. As for deleting, you should just be able to click a mod in the list and press delete on your keyboard or right-click and choose delete. If that isn't working, let me know what happens and we'll go from there.

**Comment by Fing3rz** [comment] 2021-08-19 04:49
Ah, that is unfortunate. I'm unable to delete using either of those methods.

**Comment by thommcgrath** [comment] 2021-08-19 16:47
Can you give me more information about what you're seeing? What steps are you taking, and what happens? I've just tried on both my Mac and PC, and I can't reproduce what I think you're describing. I'm able to delete mods just fine.

**Comment by Fing3rz** [comment] 2021-08-19 18:56
Sorry I should have provided more info. I was falling asleep. XD
1. Open Beacon v1.5.2b2
2. Click Blueprints
3. It defaults to Mods
4. Select one of the mods I've added, press delete, nothing
5. Right-Click one of the mods, delete is greyed out, click anyways, nothing

While I was trying again after having added a few more mods, I managed to delete some of them. It appears to only happen to the mod at the top of the list, in either sorting direction, whichever mod is at the top doesn't allow me to delete.

More info. I'm running Windows 10 Enterprise 20H2. I have installed the x64 app in the default location(program files). I'm using the local administrator account on my machine. I don't have any projects or presets or anything else open in the app. Let me know if you need more.

**Comment by thommcgrath** [comment] 2021-08-19 19:14
Bingo, that's what I needed. Yeah that's a leftover behavior because the first one in the list used to always be the "User Blueprints" mod that cannot be deleted. That's no longer true, so I need to update the behavior.

**Comment by Fing3rz** [comment] 2021-08-22 02:57
I know you've already answered this but if it were possible for the user to simply import the data dumped shootergame.log and have it create the mod entries automatically, it would be a real game changer and make the feature feel complete. This isn't me being lazy or anything, I'll do the work to add them one by one, it's just very tedious atm. Also, If you've imported multiple mods you have to uncheck each mod for every new mod entry. Clicking the column headers for checkboxes feels like it should be a toggle all button. When creating loot set entries you should be able to select multiple entries and hit spacebar or something to check them all. Perhaps that's just my Windows experience talking.

unrelated question: When adding new loot entries I see four unfamiliar Max Quality options, epic, legendary, pearlescent, perfected. What are those? I couldn't find them in the documentation.

**Comment by thommcgrath** [comment] 2021-08-22 03:04
It's just not going to happen that way. The mod needs to exist before I can start assigning blueprints to it. The entire import process exists inside the mod editor view. With some _heavy_ refactoring, it could be done, but I have other things I'd like to get done that would have more value.

There is a way to do what you're looking for. Hold Control while you click a checkbox in a column, and they will all be set to match.

Those four qualities are for greater amounts of quality on the item. Ascendent items start becoming common at around quality 20, but the value can go all the way up to 100. So those equate to 40, 60, 80, and 100 respectively.

**Comment by Fing3rz** [comment] 2021-08-22 03:28
I understand now. Thanks for the explanation.

That Control tip is huge! lol That's a new one for me. Thanks!

I misinterpreted how the quality settings worked. After reading the help article I think I get it.

**Comment by thommcgrath** [comment] 2021-09-21 17:10
Closing this now because it was implemented in 1.5.2

**Closed by thommcgrath** 2021-09-21 17:10 UTC
